### ISSUE TITLE
Update Duplicate Post microcopy and links

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-workflow#66]
The additional links that the Duplicate Post plugin add may be confusing to users unfamiliar with how the functionality behaves. There are three links/features that are added that have overlapping functionality: 

* "Clone" creates a new copy using the settings stored in the database and redirects you to the post list
* "New Draft" does the same, but then redirects you to the edit screen of the newly created copy
* "Rewrite & Republish" creates a copy intended to be a "fork" of a post, so you can make changes on that and then "merge" them back onto the original. The copy which is created is intended to be used only for this purpose, it can't be an "independent" post.

Within these three options, "Clone" and "New Draft" are essentially the same thing with minor differences:

* where the redirect takes the user after the operation completes, as described above
* "Clone" can also copy the status of the original if an option is set ("New Draft" always creates a draft) (by default, Clone does _not_ copy the post status)
* "Clone" is also available as a bulk action choice so you can select and copy multiple post in one go.

To optimize space and reduce confusion, we would like to remove the "Clone" option in favor of "New Draft". We would also like to rethink these labels and possibly come up with something that is more succinct and evocative.

![Screen Shot 2021-05-25 at 3 10 42 PM](https://user-images.githubusercontent.com/991511/119569043-6f37a480-bd6b-11eb-9c06-b8184b9465be.png)

**Todo:**
- [x] We need to decide on the actual microcopy to use and update the acceptance criteria accordingly.

**Acceptance Criteria:**
- [x] Remove "Clone" link from Quick Actions row
- [x] Rephrase "New Draft" to "Clone"
- [x] Rephrase "Rewrite & Republish" to "Create amendment" (per comment below)
* [x] Action in posts list if no amendment exists: "Create amendment"
* [x] Action in posts list if one already exists: "Edit amendment"
* [x] Annotation in posts list "Amendment of {original}"
- [x] Update the documentation and screenshots to reflect any new changes as needed
* [x] Primary action button in the block editor: "Publish Amendment"
* [x] Prepublish title: "Are you ready to publish your amendment?"
* [x] Prepublish description: "After publishing, your changes will be merged into the original post and you'll be redirected there."

**Comment by rmccue** [comment]
This requires more research for working out the phrasing, and whether we need to rename at all. I'll pick up digging into this.

We probably want to keep "Clone" as the action for consistency, but we can bikeshed on that later.

**Comment by roborourke** [comment]
Wanted to note down an idea here before I forget. What if - and it's a big if - we made the standard "Edit" link do the Rewrite & Republish behaviour. Would have to make sure it linked to any existing rewrite & republish in progress. Then perhaps add a link for "Edit live version".

This way the workflow is somewhat seamless and just the default behaviour for editing published posts. Potentially eliminates the need for 3 extra links down to just 1 for "Duplicate" or "Clone".

**Comment by rmccue** [comment]
Wild. I like it.

**Comment by jazzsequence** [comment]
This is an interesting idea. I'm not quite sold on it yet but there are definitely benefits. The only potential issue I can see is that there would be a disconnect in the behavior of the "Edit" link for draft posts vs published posts (you can't Rewrite & Republish a draft), so it might create some cognitive dissonance with the two different workflows/behaviors.

I think that might be balanced by the benefit of being able to update and create drafts of a post that's already published without affecting that published post, but it's worth keeping in mind (we'd also need to document this at the very least).

**Comment by rmccue** [comment]
Could get this out as a preview release and potentially have people try it straight away.

Could also try this with Invision prototypes and run it in front of users to see what they prefer. Would be quicker than writing code. @jazzsequence to take some screenshots and get this prepared.

Let's incorporate this into the review, and additionally @garethwelton will pick up some user research here after his return from SPRING BREAK.

**Comment by garethwelton** [comment]
Back and will get something done for this on Friday.

**Comment by rmccue** [comment]
Suggestion from @yumito via @garethwelton:

* Action in posts list if no amendment exists: "Create amendment"
* Action in posts list if one already exists: "Edit amendment" (may not be possible to detect this currently?)
* Annotation in posts list "Amendment of {original}"
* Primary action button in the block editor: "Publish Amendment"
* Prepublish title: "Are you ready to publish your amendment?"
* Prepublish description: "After publishing, your changes will be merged into the original post and you'll be redirected there."

I like it, let's rock and roll.

**Comment by roborourke** [comment]
Fixed in #73, nice one @jazzsequence
